### ISSUE TITLE
cleanup handling of common network segment for two P-DAO

### ISSUE THREAD

**Issue by nyrahul** [roll-wg/dao-projection#2]
The problem here is that there could be two targets with common network segment (with hop-by-hop routing) in between and thus proactive cleanup and no-path P-DAO needs to be handled appropriately.

**Comment by inesrob** [comment]
@nyrahul Could you please elaborate the issue further? 
From Pascal: Say you have a segment with two targets, if you lose the segment you lose both targets, If you want to update the target, you need to send the P-DAO for the same segment with the new sequence number and the new list of targets . Thank you very much

**Comment by nyrahul** [comment]
I think we can safely close this issue. The draft has undergone a tectonic shift since the time this issue was raised. The draft has a completely new section that explains cleanup of the projected DAO routes.

**Comment by inesrob** [comment]
Thank you very much, please comment during WGLC if this issues is still valid
