### ISSUE TITLE
Information Missing in VIO abbreviation

### ISSUE THREAD

**Issue by rabinsahoo** [roll-wg/dao-projection#3]
In the section 3 
"This specification introduces two new Control Message Options
 referred to as Route Projection Options (RPO). **One RPO is the
 Information option (VIO)** and the other is the Source-Routed VIO
 (SRVIO)"

I think VIA is missing in the explanation of VIO

**Comment by inesrob** [comment]
Version 23 states:

"
4.1.3.  Via Information Option

   New CMOs called the Via Information Options (VIO) are introduced for
   use in P-DAO messages as a multihop alternative to the TIO, more in
   Section 5.3."
