### ISSUE TITLE
should DAO projection have a new MOP?

### ISSUE THREAD

**Issue by mcr** [roll-wg/dao-projection#5]
moved from: https://trac.ietf.org/trac/roll/ticket/189 

Based on discussion on IETF101:

Do we need a new MOP? (3 bits get saturated) and other related to the discussion of dao-projection: How is the topology known to the root? How are the node capabilities known to the root? Complexity of mixed modes and route concatenation MOP saturation Compression of the Via Info option (so far full addresses). Loop avoidance.

**Comment by inesrob** [comment]
No needed in this draft new MOP, since flags are being used.
